# Generated by Django 6.0.7 on 2026-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Living Room', 'Living Room'), ('Wardrobe', 'Wardrobe'), ('Office', 'Office'), ('TV Unit', 'TV Unit'), ('Other', 'Other')], default='Other', max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
